import type { Opportunity } from '../interfaces/Opportunity'

/* eslint-disable perfectionist/sort-objects */
export const mockOpportunities: Opportunity[] = [
  {
    id: 1,
    title: 'مطوّر واجهات أمامية (Vue.js)',
    company: 'شركة تقنية المستقبل',
    companyInitial: 'ت',
    location: 'الرياض، حي العليا',
    city: 'الرياض',
    type: 'full_time',
    level: 'senior',
    department: 'التقنية',
    matchRate: 94,
    matchBreakdown: { skills: 96, experience: 90, education: 92, location: 100 },
    applicants: 28,
    postedAt: 'قبل يومين',
    postedDaysAgo: 2,
    isNew: true,
    isFeatured: true,
    salaryMin: 12000,
    salaryMax: 18000,
    description: 'نبحث عن مطوّر واجهات أمامية متمكّن في Vue 3 و TypeScript لبناء منتجات رقمية حديثة ضمن فريق تقني متكامل.',
    responsibilities: ['تطوير واجهات تفاعلية عالية الأداء', 'التعاون مع فرق التصميم والـ Backend', 'مراجعة الأكواد وضمان الجودة'],
    requirements: ['خبرة 4+ سنوات في تطوير الواجهات', 'إتقان Vue 3 و TypeScript', 'فهم عميق لأنماط التصميم'],
    benefits: ['تأمين طبي شامل', 'بدل سكن', 'عمل مرن', 'ميزانية تطوير مهني'],
    skills: ['Vue.js', 'TypeScript', 'Vuetify', 'REST API', 'Pinia'],
  },
  {
    id: 2,
    title: 'مهندس ذكاء اصطناعي',
    company: 'مجموعة الابتكار الرقمي',
    companyInitial: 'ا',
    location: 'عن بُعد',
    city: 'عن بُعد',
    type: 'remote',
    level: 'senior',
    department: 'التقنية',
    matchRate: 88,
    matchBreakdown: { skills: 90, experience: 85, education: 95, location: 100 },
    applicants: 41,
    postedAt: 'قبل 3 أيام',
    postedDaysAgo: 3,
    isNew: true,
    salaryMin: 20000,
    salaryMax: 28000,
    description: 'بناء نماذج معالجة لغة طبيعية وأنظمة توصية لمنصة توظيف ذكية تخدم آلاف المستخدمين.',
    responsibilities: ['تصميم وتدريب نماذج NLP', 'بناء أنظمة توصية', 'نشر النماذج في الإنتاج'],
    requirements: ['خبرة في PyTorch أو TensorFlow', 'إلمام بمعالجة اللغة الطبيعية', 'ماجستير في مجال ذي صلة (مفضّل)'],
    benefits: ['عمل عن بُعد بالكامل', 'أسهم في الشركة', 'مؤتمرات عالمية'],
    skills: ['Python', 'NLP', 'PyTorch', 'FastAPI', 'MLOps'],
  },
  {
    id: 3,
    title: 'مصمم تجربة مستخدم UX',
    company: 'استوديو رؤية للتصميم',
    companyInitial: 'ر',
    location: 'جدة، حي الروضة',
    city: 'جدة',
    type: 'part_time',
    level: 'mid',
    department: 'التصميم',
    matchRate: 81,
    matchBreakdown: { skills: 82, experience: 78, education: 85, location: 80 },
    applicants: 17,
    postedAt: 'قبل أسبوع',
    postedDaysAgo: 7,
    salaryMin: 8000,
    salaryMax: 12000,
    description: 'تصميم تجارب مستخدم سلسة لمنصات الويب والجوال مع التركيز على البحث والاختبار.',
    responsibilities: ['إجراء أبحاث المستخدم', 'تصميم النماذج الأولية', 'اختبار قابلية الاستخدام'],
    requirements: ['إتقان Figma', 'محفظة أعمال قوية', 'خبرة في أبحاث المستخدم'],
    benefits: ['مرونة في العمل', 'بيئة إبداعية'],
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
  },
  {
    id: 4,
    title: 'محلل بيانات أول',
    company: 'بنك المعرفة',
    companyInitial: 'ب',
    location: 'الدمام، الكورنيش',
    city: 'الدمام',
    type: 'full_time',
    level: 'mid',
    department: 'البيانات',
    matchRate: 76,
    matchBreakdown: { skills: 78, experience: 72, education: 80, location: 74 },
    applicants: 33,
    postedAt: 'قبل 5 أيام',
    postedDaysAgo: 5,
    salaryMin: 14000,
    salaryMax: 19000,
    description: 'تحليل بيانات الأعمال وبناء لوحات تحليلية تدعم اتخاذ القرار في القطاع المصرفي.',
    responsibilities: ['بناء لوحات Power BI', 'تحليل اتجاهات الأعمال', 'إعداد التقارير الدورية'],
    requirements: ['إتقان SQL', 'خبرة في Power BI', 'مهارات إحصائية قوية'],
    benefits: ['تأمين طبي', 'مكافآت أداء', 'بدل مواصلات'],
    skills: ['SQL', 'Power BI', 'Excel', 'Statistics', 'Python'],
  },
  {
    id: 5,
    title: 'مدير تسويق رقمي',
    company: 'علامة تجارية ناشئة',
    companyInitial: 'ع',
    location: 'الرياض، حي الملقا',
    city: 'الرياض',
    type: 'full_time',
    level: 'lead',
    department: 'التسويق',
    matchRate: 72,
    matchBreakdown: { skills: 70, experience: 75, education: 72, location: 100 },
    applicants: 22,
    postedAt: 'قبل يوم',
    postedDaysAgo: 1,
    isNew: true,
    salaryMin: 15000,
    salaryMax: 22000,
    description: 'قيادة استراتيجيات التسويق الرقمي وإدارة الحملات عبر القنوات المختلفة.',
    responsibilities: ['وضع الاستراتيجية التسويقية', 'إدارة ميزانية الحملات', 'قيادة فريق التسويق'],
    requirements: ['خبرة 6+ سنوات في التسويق الرقمي', 'إتقان Google Ads و SEO', 'مهارات قيادية'],
    benefits: ['أسهم', 'بدل سكن', 'عمولات أداء'],
    skills: ['SEO', 'Google Ads', 'Content', 'Analytics', 'Social Media'],
  },
  {
    id: 6,
    title: 'مهمة: تطوير صفحة هبوط تسويقية',
    company: 'متجر إلكتروني',
    companyInitial: 'م',
    location: 'عن بُعد',
    city: 'عن بُعد',
    type: 'freelance',
    level: 'mid',
    department: 'التقنية',
    matchRate: 90,
    matchBreakdown: { skills: 92, experience: 88, education: 85, location: 100 },
    applicants: 9,
    postedAt: 'قبل يومين',
    postedDaysAgo: 2,
    salaryMin: 3000,
    salaryMax: 3000,
    description: 'تصميم وتطوير صفحة هبوط تسويقية متجاوبة خلال أسبوع واحد.',
    responsibilities: ['تصميم واجهة الصفحة', 'تطويرها بشكل متجاوب', 'تحسين الأداء و SEO'],
    requirements: ['إتقان HTML/CSS/JS', 'حس تصميمي جيد', 'الالتزام بالموعد'],
    benefits: ['دفع فوري عند التسليم', 'فرصة لمشاريع مستقبلية'],
    skills: ['HTML', 'CSS', 'JavaScript', 'Responsive Design'],
  },
  {
    id: 7,
    title: 'مطوّر Backend (Laravel)',
    company: 'شركة الحلول الذكية',
    companyInitial: 'ح',
    location: 'الرياض، حي الياسمين',
    city: 'الرياض',
    type: 'full_time',
    level: 'senior',
    department: 'التقنية',
    matchRate: 85,
    matchBreakdown: { skills: 88, experience: 82, education: 80, location: 100 },
    applicants: 36,
    postedAt: 'قبل 4 أيام',
    postedDaysAgo: 4,
    salaryMin: 16000,
    salaryMax: 23000,
    description: 'بناء واجهات برمجية قوية وقابلة للتوسّع باستخدام Laravel لمنصات متعددة.',
    responsibilities: ['تصميم قواعد البيانات', 'بناء REST APIs', 'ضمان الأمان والأداء'],
    requirements: ['خبرة 5+ سنوات في Laravel', 'إتقان MySQL', 'فهم أنماط المعمارية'],
    benefits: ['تأمين طبي شامل', 'بدل سكن ومواصلات', 'عمل هجين'],
    skills: ['PHP', 'Laravel', 'MySQL', 'Redis', 'Docker'],
  },
  {
    id: 8,
    title: 'مطوّر تطبيقات جوال (Flutter)',
    company: 'تطبيقات المدن الذكية',
    companyInitial: 'ت',
    location: 'الخبر',
    city: 'الخبر',
    type: 'full_time',
    level: 'mid',
    department: 'التقنية',
    matchRate: 79,
    matchBreakdown: { skills: 80, experience: 76, education: 82, location: 78 },
    applicants: 24,
    postedAt: 'قبل 6 أيام',
    postedDaysAgo: 6,
    salaryMin: 13000,
    salaryMax: 19000,
    description: 'تطوير تطبيقات جوال عالية الجودة لنظامي iOS و Android باستخدام Flutter.',
    responsibilities: ['تطوير التطبيقات', 'التكامل مع الـ APIs', 'النشر على المتاجر'],
    requirements: ['خبرة في Flutter و Dart', 'نشر تطبيقات سابقة', 'فهم إدارة الحالة'],
    benefits: ['تأمين طبي', 'بدل جهاز', 'مكافآت'],
    skills: ['Flutter', 'Dart', 'Firebase', 'REST API'],
  },
  {
    id: 9,
    title: 'أخصائي موارد بشرية',
    company: 'مجموعة الرواد',
    companyInitial: 'ر',
    location: 'الرياض، حي السليمانية',
    city: 'الرياض',
    type: 'full_time',
    level: 'mid',
    department: 'الموارد البشرية',
    matchRate: 64,
    matchBreakdown: { skills: 60, experience: 68, education: 70, location: 100 },
    applicants: 48,
    postedAt: 'قبل 8 أيام',
    postedDaysAgo: 8,
    salaryMin: 9000,
    salaryMax: 13000,
    description: 'إدارة عمليات التوظيف والتطوير المؤسسي وتحسين تجربة الموظفين.',
    responsibilities: ['إدارة التوظيف', 'تطوير سياسات الموارد البشرية', 'قياس رضا الموظفين'],
    requirements: ['خبرة 3+ سنوات', 'شهادة في الموارد البشرية', 'مهارات تواصل ممتازة'],
    benefits: ['تأمين طبي', 'بيئة عمل محفّزة'],
    skills: ['التوظيف', 'إدارة الأداء', 'العلاقات المهنية'],
  },
  {
    id: 10,
    title: 'مصمم جرافيك',
    company: 'وكالة الإبداع',
    companyInitial: 'و',
    location: 'جدة، حي الحمراء',
    city: 'جدة',
    type: 'part_time',
    level: 'entry',
    department: 'التصميم',
    matchRate: 70,
    matchBreakdown: { skills: 72, experience: 65, education: 75, location: 68 },
    applicants: 31,
    postedAt: 'قبل 3 أيام',
    postedDaysAgo: 3,
    isNew: true,
    salaryMin: 5000,
    salaryMax: 8000,
    description: 'إنتاج تصاميم بصرية إبداعية للحملات التسويقية ومنصات التواصل الاجتماعي.',
    responsibilities: ['تصميم الهويات البصرية', 'إنتاج محتوى السوشيال ميديا', 'التعاون مع فريق التسويق'],
    requirements: ['إتقان Adobe Suite', 'محفظة أعمال', 'حس فني عالٍ'],
    benefits: ['مرونة', 'بيئة إبداعية'],
    skills: ['Photoshop', 'Illustrator', 'Branding', 'Motion'],
  },
  {
    id: 11,
    title: 'مهندس DevOps',
    company: 'البنية السحابية',
    companyInitial: 'ب',
    location: 'عن بُعد',
    city: 'عن بُعد',
    type: 'remote',
    level: 'senior',
    department: 'التقنية',
    matchRate: 83,
    matchBreakdown: { skills: 85, experience: 80, education: 78, location: 100 },
    applicants: 19,
    postedAt: 'قبل يومين',
    postedDaysAgo: 2,
    isNew: true,
    isFeatured: true,
    salaryMin: 18000,
    salaryMax: 26000,
    description: 'أتمتة البنية التحتية وبناء خطوط CI/CD موثوقة على السحابة.',
    responsibilities: ['إدارة البنية على AWS', 'بناء خطوط CI/CD', 'مراقبة الأنظمة'],
    requirements: ['خبرة في Kubernetes', 'إتقان AWS', 'خبرة في Terraform'],
    benefits: ['عمل عن بُعد', 'شهادات معتمدة مدفوعة', 'أسهم'],
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Docker'],
  },
  {
    id: 12,
    title: 'مدير مشاريع تقنية',
    company: 'شركة تقنية المستقبل',
    companyInitial: 'ت',
    location: 'الرياض، حي العليا',
    city: 'الرياض',
    type: 'full_time',
    level: 'lead',
    department: 'إدارة المشاريع',
    matchRate: 68,
    matchBreakdown: { skills: 65, experience: 72, education: 70, location: 100 },
    applicants: 27,
    postedAt: 'قبل أسبوع',
    postedDaysAgo: 7,
    salaryMin: 20000,
    salaryMax: 28000,
    description: 'قيادة مشاريع تقنية معقدة من التخطيط حتى التسليم ضمن منهجيات Agile.',
    responsibilities: ['إدارة دورة حياة المشروع', 'تنسيق الفرق', 'إدارة المخاطر والميزانية'],
    requirements: ['شهادة PMP', 'خبرة في Agile/Scrum', '7+ سنوات خبرة'],
    benefits: ['بدل سكن', 'تأمين عائلي', 'مكافآت سنوية'],
    skills: ['Agile', 'Scrum', 'Jira', 'Risk Management'],
  },
  {
    id: 13,
    title: 'كاتب محتوى تسويقي',
    company: 'منصة المحتوى العربي',
    companyInitial: 'م',
    location: 'عن بُعد',
    city: 'عن بُعد',
    type: 'part_time',
    level: 'entry',
    department: 'التسويق',
    matchRate: 61,
    matchBreakdown: { skills: 58, experience: 64, education: 62, location: 100 },
    applicants: 52,
    postedAt: 'قبل 9 أيام',
    postedDaysAgo: 9,
    salaryMin: 4000,
    salaryMax: 7000,
    description: 'كتابة محتوى تسويقي جذّاب ومحسّن لمحركات البحث باللغة العربية.',
    responsibilities: ['كتابة المقالات والمحتوى', 'تحسين SEO', 'إدارة تقويم المحتوى'],
    requirements: ['مهارات كتابة ممتازة', 'إلمام بـ SEO', 'سرعة في الإنجاز'],
    benefits: ['عمل عن بُعد', 'ساعات مرنة'],
    skills: ['الكتابة', 'SEO', 'التدقيق اللغوي'],
  },
  {
    id: 14,
    title: 'مهندس اختبار برمجيات QA',
    company: 'الحلول الذكية',
    companyInitial: 'ح',
    location: 'الرياض، حي الياسمين',
    city: 'الرياض',
    type: 'full_time',
    level: 'mid',
    department: 'التقنية',
    matchRate: 74,
    matchBreakdown: { skills: 76, experience: 70, education: 74, location: 100 },
    applicants: 21,
    postedAt: 'قبل 4 أيام',
    postedDaysAgo: 4,
    salaryMin: 11000,
    salaryMax: 16000,
    description: 'ضمان جودة المنتجات الرقمية عبر الاختبار اليدوي والآلي.',
    responsibilities: ['كتابة حالات الاختبار', 'أتمتة الاختبارات', 'تتبّع الأخطاء'],
    requirements: ['خبرة في Selenium أو Cypress', 'فهم دورة حياة الاختبار', 'دقة عالية'],
    benefits: ['تأمين طبي', 'عمل هجين'],
    skills: ['Cypress', 'Selenium', 'Test Automation', 'Jest'],
  },
  {
    id: 15,
    title: 'محاسب مالي',
    company: 'مجموعة الرواد',
    companyInitial: 'ر',
    location: 'الرياض، حي السليمانية',
    city: 'الرياض',
    type: 'full_time',
    level: 'mid',
    department: 'المالية',
    matchRate: 58,
    matchBreakdown: { skills: 55, experience: 60, education: 65, location: 100 },
    applicants: 44,
    postedAt: 'قبل 10 أيام',
    postedDaysAgo: 10,
    salaryMin: 8000,
    salaryMax: 12000,
    description: 'إدارة الحسابات المالية وإعداد التقارير والامتثال للمعايير المحاسبية.',
    responsibilities: ['إعداد القوائم المالية', 'إدارة الفواتير', 'المطابقة البنكية'],
    requirements: ['بكالوريوس محاسبة', 'خبرة 3+ سنوات', 'إتقان Excel'],
    benefits: ['تأمين طبي', 'بدل مواصلات'],
    skills: ['المحاسبة', 'Excel', 'التقارير المالية'],
  },
  {
    id: 16,
    title: 'أخصائي أمن سيبراني',
    company: 'درع الأمن الرقمي',
    companyInitial: 'د',
    location: 'الرياض، حي الصحافة',
    city: 'الرياض',
    type: 'full_time',
    level: 'senior',
    department: 'الأمن',
    matchRate: 80,
    matchBreakdown: { skills: 82, experience: 78, education: 80, location: 100 },
    applicants: 15,
    postedAt: 'قبل 3 أيام',
    postedDaysAgo: 3,
    isNew: true,
    salaryMin: 17000,
    salaryMax: 25000,
    description: 'حماية الأنظمة والشبكات من التهديدات السيبرانية وإدارة الاستجابة للحوادث.',
    responsibilities: ['تقييم الثغرات', 'مراقبة التهديدات', 'الاستجابة للحوادث'],
    requirements: ['شهادة CEH أو CISSP', 'خبرة في اختبار الاختراق', 'معرفة بأنظمة SIEM'],
    benefits: ['تأمين شامل', 'شهادات مدفوعة', 'بدل سكن'],
    skills: ['Penetration Testing', 'SIEM', 'Network Security', 'Incident Response'],
  },
  {
    id: 17,
    title: 'مطوّر Full Stack',
    company: 'مجموعة الابتكار الرقمي',
    companyInitial: 'ا',
    location: 'عن بُعد',
    city: 'عن بُعد',
    type: 'remote',
    level: 'mid',
    department: 'التقنية',
    matchRate: 87,
    matchBreakdown: { skills: 89, experience: 84, education: 82, location: 100 },
    applicants: 38,
    postedAt: 'قبل يوم',
    postedDaysAgo: 1,
    isNew: true,
    salaryMin: 15000,
    salaryMax: 21000,
    description: 'تطوير تطبيقات ويب متكاملة من الواجهة حتى الخادم ضمن فريق رشيق.',
    responsibilities: ['تطوير الواجهات والخوادم', 'تصميم قواعد البيانات', 'المشاركة في القرارات التقنية'],
    requirements: ['خبرة في Vue و Node.js', 'فهم قواعد البيانات', 'روح الفريق'],
    benefits: ['عمل عن بُعد', 'ساعات مرنة', 'أسهم'],
    skills: ['Vue.js', 'Node.js', 'PostgreSQL', 'TypeScript', 'REST API'],
  },
  {
    id: 18,
    title: 'استشارة: مراجعة معمارية نظام',
    company: 'شركة ناشئة في التقنية المالية',
    companyInitial: 'ف',
    location: 'عن بُعد',
    city: 'عن بُعد',
    type: 'freelance',
    level: 'lead',
    department: 'التقنية',
    matchRate: 91,
    matchBreakdown: { skills: 93, experience: 95, education: 85, location: 100 },
    applicants: 6,
    postedAt: 'قبل يومين',
    postedDaysAgo: 2,
    isFeatured: true,
    salaryMin: 8000,
    salaryMax: 8000,
    description: 'مراجعة معمارية نظام فينتك وتقديم توصيات لتحسين القابلية للتوسّع خلال أسبوعين.',
    responsibilities: ['تقييم المعمارية الحالية', 'تحديد نقاط الاختناق', 'تقديم خارطة طريق'],
    requirements: ['خبرة قيادية في أنظمة موزّعة', 'معرفة بالفينتك', 'مهارات تواصل ممتازة'],
    benefits: ['أجر تنافسي للاستشارة', 'مرونة كاملة'],
    skills: ['System Design', 'Microservices', 'Scalability', 'Cloud'],
  },
]
/* eslint-enable perfectionist/sort-objects */

export function getOpportunityById(id: number): Opportunity | undefined {
  return mockOpportunities.find(o => o.id === id)
}
