import type { Opportunity } from '../interfaces/Opportunity'

export const mockOpportunities: Opportunity[] = [
  {
    id: 1,
    title: 'مطوّر واجهات أمامية (Vue.js)',
    company: 'شركة تقنية المستقبل',
    location: 'الرياض',
    type: 'full_time',
    matchRate: 94,
    applicants: 28,
    postedAt: 'قبل يومين',
    isNew: true,
    isFeatured: true,
    salaryRange: '12,000 - 18,000 ريal',
    description: 'نبحث عن مطوّر واجهات أمامية متمكّن في Vue 3 و TypeScript لبناء منتجات رقمية حديثة.',
    skills: ['Vue.js', 'TypeScript', 'Vuetify', 'REST API'],
  },
  {
    id: 2,
    title: 'مهندس ذكاء اصطناعي',
    company: 'مجموعة الابتكار',
    location: 'عن بُعد',
    type: 'remote',
    matchRate: 88,
    applicants: 41,
    postedAt: 'قبل 3 أيام',
    isNew: true,
    salaryRange: '20,000 - 28,000 ريال',
    description: 'بناء نماذج معالجة لغة طبيعية وأنظمة توصية لمنصة توظيف ذكية.',
    skills: ['Python', 'NLP', 'PyTorch', 'FastAPI'],
  },
  {
    id: 3,
    title: 'مصمم تجربة مستخدم UX',
    company: 'استوديو رؤية',
    location: 'جدة',
    type: 'part_time',
    matchRate: 81,
    applicants: 17,
    postedAt: 'قبل أسبوع',
    salaryRange: '8,000 - 12,000 ريال',
    description: 'تصميم تجارب مستخدم سلسة لمنصات الويب والجوال.',
    skills: ['Figma', 'User Research', 'Prototyping'],
  },
  {
    id: 4,
    title: 'محلل بيانات',
    company: 'بنك المعرفة',
    location: 'الدمام',
    type: 'full_time',
    matchRate: 76,
    applicants: 33,
    postedAt: 'قبل 5 أيام',
    salaryRange: '14,000 - 19,000 ريال',
    description: 'تحليل بيانات الأعمال وبناء لوحات تحليلية تدعم القرار.',
    skills: ['SQL', 'Power BI', 'Excel', 'Statistics'],
  },
  {
    id: 5,
    title: 'مدير تسويق رقمي',
    company: 'علامة تجارية ناشئة',
    location: 'الرياض',
    type: 'full_time',
    matchRate: 72,
    applicants: 22,
    postedAt: 'قبل يوم',
    isNew: true,
    salaryRange: '15,000 - 22,000 ريال',
    description: 'قيادة استراتيجيات التسويق الرقمي وإدارة الحملات.',
    skills: ['SEO', 'Google Ads', 'Content', 'Analytics'],
  },
  {
    id: 6,
    title: 'مهمة: تطوير صفحة هبوط',
    company: 'متجر إلكتروني',
    location: 'عن بُعد',
    type: 'task',
    matchRate: 90,
    applicants: 9,
    postedAt: 'قبل يومين',
    salaryRange: '3,000 ريال (مهمة)',
    description: 'تصميم وتطوير صفحة هبوط تسويقية متجاوبة خلال أسبوع.',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
]

export function getOpportunityById(id: number): Opportunity | undefined {
  return mockOpportunities.find(o => o.id === id)
}
